#!/bin/sh
# install.sh — install Pibuz from the latest GitHub release, and reboot into it.
#
#   curl -fsSL https://philipvinc.github.io/pibuz/install.sh | sudo sh
#
# TWO SHAPES, because a moOde box and a plain Linux box start a daemon
# differently and the script must not fight the one it is on:
#
#   moOde  -> swap the binary in place, nothing else.
#     moOde starts the daemon ITSELF: `startQobuz()` in renderer.php pushes the
#     audio device, the quality cap and the hook script, then runs `pibuz run &`,
#     and `stopQobuz()` does `killall pibuz`. There is no systemd unit anywhere
#     on moOde, so installing one would put a SECOND daemon on the same hw:
#     device. This replaces the file and lets the reboot hand it to moOde.
#
#   anything else -> binary + a systemd SYSTEM unit, enabled.
#     Generated by the binary for the box's own user, so it starts at boot with
#     no `loginctl enable-linger` and does not die with your SSH session.
#
# WHERE the binary goes is not a constant: it replaces whatever `pibuz` PATH
# already resolves to, because that is the one moOde runs (`sysCmd('pibuz run')`
# goes through PATH, and /usr/local/bin precedes /usr/bin on Debian — install to
# /usr/bin under an existing /usr/local/bin copy and nothing changes). With no
# pibuz installed at all it lands in /usr/local/bin, which is where moOde's own
# tooling lives and where this project's deploy script has always put it.
#
# First install on moOde? Renderer Config -> Qobuz Connect -> Install is the
# supported path: it builds the moOde package, pushes moOde's settings and wires
# the event hook. This script is for jumping to a release moOde does not offer
# yet. `--standalone` forces the systemd path on a moOde box instead.
#
# Options:
#   --version X.Y.Z   install this release instead of the latest
#   --user NAME       run as NAME (standalone only; default $SUDO_USER, then uid 1000)
#   --standalone      force the systemd path even on moOde
#   --no-reboot       install and enable, but leave the reboot to you
set -eu

REPO="PhilipVinc/pibuz"
# The moOde generation this is tested against. A different major warns; it never
# refuses, because pibuz talks to ALSA and Qobuz, not to moOde.
MOODE_MAJOR="10"
# PIBUZ_BIN / PIBUZ_UNIT override the resolved paths, so the script can be
# exercised without touching a real box. BIN is resolved below.
UNIT="${PIBUZ_UNIT:-/etc/systemd/system/pibuz.service}"
VERSION=""
RUN_AS="${PIBUZ_USER:-${SUDO_USER:-}}"
REBOOT=1
FORCE_STANDALONE=0

say() { echo "pibuz: $*"; }
warn() { echo "pibuz: warning: $*" >&2; }
die() {
	echo "pibuz: error: $*" >&2
	exit 1
}

while [ $# -gt 0 ]; do
	case "$1" in
	--version) VERSION="${2:?--version needs X.Y.Z}"; shift 2 ;;
	--user) RUN_AS="${2:?--user needs a name}"; shift 2 ;;
	--standalone) FORCE_STANDALONE=1; shift ;;
	--no-reboot) REBOOT=0; shift ;;
	-h | --help) sed -n '2,30p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
	*) die "unknown option '$1'" ;;
	esac
done

[ "$(id -u)" = "0" ] || die "run this as root: curl -fsSL <url> | sudo sh"

# ---- arch -------------------------------------------------------------------
case "$(uname -m)" in
aarch64 | arm64) ARCH="aarch64" ;;
x86_64 | amd64) ARCH="amd64" ;;
*) die "no prebuilt binary for $(uname -m) — moOde 9+ is 64-bit; build from source" ;;
esac

# ---- which box is this ------------------------------------------------------
moode_release() {
	if command -v moodeutl >/dev/null 2>&1; then
		moodeutl --mooderel 2>/dev/null | awk '{print $1; exit}'
		return
	fi
	for f in /var/www/footer.min.php /var/www/footer.php; do
		[ -r "$f" ] || continue
		sed -n 's/.*Release: \([0-9][0-9.]*\).*/\1/p' "$f" | head -1
		return
	done
}
MOODE="$(moode_release || true)"
# The version moOde's own UI reports: `dpkg-query ... | grep moode` in
# renderer.php. Absent on a box where the binary was installed by hand.
DEB="$(dpkg-query --showformat='${Version}' --show pibuz 2>/dev/null || true)"

# ---- where the binary goes --------------------------------------------------
# Replace what PATH resolves, or the file the package owns, or fall back to
# /usr/local/bin. PIBUZ_BIN overrides all of it.
EXISTING="$(command -v pibuz 2>/dev/null || true)"
if [ -n "${PIBUZ_BIN:-}" ]; then
	BIN="$PIBUZ_BIN"
elif [ -n "$EXISTING" ]; then
	BIN="$EXISTING"
elif [ -n "$DEB" ] && [ -e /usr/bin/pibuz ]; then
	BIN="/usr/bin/pibuz"
else
	BIN="/usr/local/bin/pibuz"
fi

if [ -n "$MOODE" ] && [ "$FORCE_STANDALONE" = "0" ]; then
	MODE="moode"
	[ "${MOODE%%.*}" = "$MOODE_MAJOR" ] ||
		warn "this is moOde $MOODE; pibuz is tested on moOde $MOODE_MAJOR.x"
	say "moOde $MOODE${DEB:+, Qobuz Connect package $DEB}"
	if [ -z "$EXISTING" ] && [ -z "$DEB" ]; then
		warn "no pibuz on this box yet. This drops in the binary, but moOde still
  needs Renderer Config -> Qobuz Connect to configure and start it."
	fi
else
	MODE="standalone"
	[ -z "$MOODE" ] || say "moOde $MOODE — installing standalone, outside moOde's control"
	[ -n "$RUN_AS" ] || RUN_AS="$(getent passwd 1000 | cut -d: -f1)"
	[ -n "$RUN_AS" ] || die "could not tell which user to run as — pass --user NAME"
	id "$RUN_AS" >/dev/null 2>&1 || die "no such user: $RUN_AS"
fi

# ---- fetch ------------------------------------------------------------------
if [ -n "$VERSION" ]; then
	URL="https://github.com/$REPO/releases/download/v$VERSION/pibuz-$VERSION-linux-$ARCH.tar.gz"
else
	URL="$(curl -fsSL "https://api.github.com/repos/$REPO/releases/latest" |
		grep -om1 "https://[^\"]*-linux-$ARCH\.tar\.gz")" ||
		die "could not reach the GitHub release API"
	[ -n "$URL" ] || die "the latest release has no linux-$ARCH asset"
	VERSION="$(echo "$URL" | sed -n 's|.*/pibuz-\(.*\)-linux-.*|\1|p')"
fi

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT HUP INT TERM
say "downloading $VERSION ($ARCH)"
curl -fsSL "$URL" -o "$TMP/pibuz.tar.gz" || die "download failed: $URL"

# The .sha256 is published beside every asset. A truncated download is the
# failure that actually happens on a Pi, and it would install a broken binary.
if curl -fsSL "$URL.sha256" -o "$TMP/pibuz.sha256" 2>/dev/null; then
	if command -v sha256sum >/dev/null 2>&1; then
		want="$(cut -d' ' -f1 "$TMP/pibuz.sha256")"
		got="$(sha256sum "$TMP/pibuz.tar.gz" | cut -d' ' -f1)"
		[ "$want" = "$got" ] || die "checksum mismatch — refusing to install"
	else
		warn "no sha256sum on this box; skipping checksum"
	fi
else
	warn "no published checksum for this asset; skipping"
fi

tar -xzf "$TMP/pibuz.tar.gz" -C "$TMP" || die "the tarball did not unpack"
SRC="$TMP/pibuz-$VERSION-linux-$ARCH/pibuz"
[ -f "$SRC" ] || die "no pibuz binary inside the tarball"

# ---- install ----------------------------------------------------------------
# `install` unlinks the destination first, so this replaces a RUNNING binary
# without "Text file busy". The running process keeps the old inode until it is
# restarted, which the reboot below does.
install -m 755 "$SRC" "$BIN" || die "could not write $BIN"
say "installed $VERSION at $BIN"

# /usr/local/bin precedes /usr/bin: another copy earlier on PATH is the one that
# would actually run, and this install would look like it did nothing.
for other in /usr/local/bin/pibuz /usr/bin/pibuz; do
	[ -n "${PIBUZ_BIN:-}" ] && break # an overridden path says nothing about PATH
	[ "$other" = "$BIN" ] && continue
	[ -e "$other" ] || continue
	case "$BIN:$other" in
	/usr/bin/pibuz:/usr/local/bin/pibuz)
		warn "$other shadows $BIN on PATH and was NOT replaced — remove it: sudo rm $other" ;;
	*)
		say "note: an older copy remains at $other (unused; $BIN wins on PATH)" ;;
	esac
done

if [ "$MODE" = "moode" ]; then
	# No unit, no enable: worker.php calls startQobuz() at boot and on every
	# renderer toggle. Leave moOde in charge of starting and stopping it.
	say "left the service alone — moOde starts pibuz itself"
	if [ -n "$DEB" ]; then
		warn "dpkg still records $DEB, so moOde's UI keeps showing that version, and
  Renderer Config -> Qobuz Connect -> Upgrade rebuilds moOde's pinned tag over
  this binary. That is the price of jumping ahead of moOde's package."
	fi
else
	# The binary writes its own unit, resolving User=, HOME= and ExecStart= for
	# the target user. Its stderr is an install hint for humans; drop it.
	"$BIN" service systemd --system --user "$RUN_AS" --bin "$BIN" >"$TMP/unit" 2>/dev/null ||
		die "could not generate the unit file"
	[ -s "$TMP/unit" ] || die "generated an empty unit file"
	install -m 644 "$TMP/unit" "$UNIT"
	say "wrote $UNIT (User=$RUN_AS)"
	systemctl daemon-reload
	systemctl enable pibuz >/dev/null 2>&1 || die "systemctl enable pibuz failed"

	# An older recipe installed a systemd USER unit. Two units, one device_uuid,
	# one ALSA device: whichever wins, the other logs device-busy forever.
	HOME_DIR="$(getent passwd "$RUN_AS" | cut -d: -f6)"
	if [ -n "$HOME_DIR" ] && [ -e "$HOME_DIR/.config/systemd/user/default.target.wants/pibuz.service" ]; then
		warn "a systemd USER unit is also enabled for $RUN_AS — disable it:"
		warn "  sudo -u $RUN_AS XDG_RUNTIME_DIR=/run/user/$(id -u "$RUN_AS") systemctl --user disable --now pibuz"
	fi
fi

echo
if [ "$MODE" = "moode" ]; then
	say "done. After the reboot moOde starts $VERSION; check Renderer Config."
else
	say "done. After the reboot pibuz runs at boot and appears in the Qobuz app."
	say "To pick a specific DAC or name the device:  pibuz setup   (as $RUN_AS)"
fi
say "Status:  pibuz status"

if [ "$REBOOT" = "1" ]; then
	echo
	say "rebooting in 5 seconds — Ctrl-C to stay up"
	sleep 5
	systemctl reboot
fi
